---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install Python"
  become: true
  apt:
    name: ["python"]
    state: latest
    update_cache: yes

- name: "Install Nodejs"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present

# - name: "create backend-app directory"
#   file:
#     path: ~/backend-app
#     state: directory
#     #mode: '0755'
- name: "Create backend-app directory"
  file:
    path: /home/ubuntu/backend-app
    state: directory

#Already passed in config.yml
# - name: "extract zipped artifact"
#   become: true
#   unarchive:
#     src: artifact.tar.gz
#     dest: ~/backend-app
- name: 'extract the tar/zipped file'
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend-app

# - name: "install Node Dependences"
#   shell: |
#     cd ~/backend-app
#     npm install
# install backend dependencies
- name: 'install backend-app dependencies'
  become: true
  shell: |
    cd /home/ubuntu/backend-app
    npm install

# - name: "Use PM2 to run backend-app"
#   shell: |
#     cd ~/backend-app/dist
#     #pm2 stop default
#     pm2 start npm -- start
#     ##pm2 start main.js
#     pm2 logs
#   register: execute_node
- name: 'start the app'
  become: true
  shell: |
    cd /home/ubuntu/backend-app
    pm2 start npm -- start
  register: backend_app

# - name: "Configure pm2 to start as service"
#   become: true
#   shell: |
#     env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu